version: "2"

services:

  database:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DAV_URI=$DAV_URI
        - DAV_USR=$DAV_USR
        - DAV_PWD=$DAV_PWD
    privileged: true
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: always

  keycloakServer:
    image: jboss/keycloak
    hostname: "pilot.$DOMAIN"
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: $KEYCLOAK_PASSWORD
      KEYCLOAK_LOGLEVEL: WARNING
      PROXY_ADDRESS_FORWARDING: 'true'
      DB_VENDOR: POSTGRES
      DB_ADDR: database
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
    command: "-b 0.0.0.0"
    restart: always
